-- Smart City Traffic Database Schema
-- This script creates all necessary tables

-- Table 1: Raw traffic data from sensors
CREATE TABLE IF NOT EXISTS traffic_raw (
    id SERIAL PRIMARY KEY,
    sensor_id VARCHAR(10) NOT NULL,
    location VARCHAR(100) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    vehicle_count INTEGER NOT NULL,
    avg_speed INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table 2: Critical traffic alerts (congestion events)
CREATE TABLE IF NOT EXISTS traffic_alerts (
    id SERIAL PRIMARY KEY,
    sensor_id VARCHAR(10) NOT NULL,
    location VARCHAR(100) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    vehicle_count INTEGER NOT NULL,
    avg_speed INTEGER NOT NULL,
    congestion_level VARCHAR(20) DEFAULT 'HIGH',
    alert_message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table 3: Daily summary statistics (for batch reports)
CREATE TABLE IF NOT EXISTS daily_traffic_summary (
    id SERIAL PRIMARY KEY,
    report_date DATE NOT NULL,
    sensor_id VARCHAR(10) NOT NULL,
    location VARCHAR(100) NOT NULL,
    peak_hour INTEGER,
    total_vehicles INTEGER,
    avg_daily_speed DECIMAL(5,2),
    congestion_count INTEGER,
    recommendation TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(report_date, sensor_id)
);

-- Create indexes for better query performance
CREATE INDEX idx_traffic_raw_timestamp ON traffic_raw(timestamp);
CREATE INDEX idx_traffic_raw_sensor ON traffic_raw(sensor_id);
CREATE INDEX idx_alerts_timestamp ON traffic_alerts(timestamp);
CREATE INDEX idx_summary_date ON daily_traffic_summary(report_date);

-- Create a view for quick analytics
CREATE OR REPLACE VIEW v_hourly_traffic AS
SELECT 
    sensor_id,
    location,
    DATE_TRUNC('hour', timestamp) as hour,
    COUNT(*) as reading_count,
    AVG(vehicle_count) as avg_vehicles,
    AVG(avg_speed) as avg_speed,
    COUNT(CASE WHEN avg_speed < 10 THEN 1 END) as congestion_events
FROM traffic_raw
GROUP BY sensor_id, location, DATE_TRUNC('hour', timestamp)
ORDER BY hour DESC;

-- Insert some test data (optional - for testing)
-- COMMENT OUT AFTER FIRST RUN
/*
INSERT INTO traffic_raw (sensor_id, location, timestamp, vehicle_count, avg_speed) VALUES
('A', 'Galle Road Junction', NOW(), 45, 25),
('B', 'Baseline Road Junction', NOW(), 32, 35),
('C', 'Duplication Road Junction', NOW(), 28, 40),
('D', 'Marine Drive Junction', NOW(), 50, 15);
*/

COMMENT ON TABLE traffic_raw IS 'Stores all raw sensor readings';
COMMENT ON TABLE traffic_alerts IS 'Stores critical congestion alerts for immediate action';
COMMENT ON TABLE daily_traffic_summary IS 'Stores daily aggregated statistics generated by Airflow';